export const MODULE_CONFIG = {
  vocabulary: {
    enabled: true,
    priority: 1,
    confidenceThreshold: 0.3,
    maxEntries: 10000,
    cacheSize: 1000,
    seedFile: "seed/vocabulary.json",
    learntFile: "learnt/vocabulary.json",
    apiEndpoints: {
      dictionary: "https://api.dictionaryapi.dev/api/v2/entries/en",
    },
  },
  mathematics: {
    enabled: true,
    priority: 2,
    confidenceThreshold: 0.4,
    maxEntries: 5000,
    cacheSize: 500,
    seedFile: "seed/mathematics.json",
    learntFile: "learnt/mathematics.json",
  },
  facts: {
    enabled: true,
    priority: 3,
    confidenceThreshold: 0.3,
    maxEntries: 15000,
    cacheSize: 2000,
    seedFile: "seed/facts.json",
    learntFile: "learnt/facts.json",
    apiEndpoints: {
      wikipedia: "https://en.wikipedia.org/api/rest_v1/page/summary",
    },
  },
  coding: {
    enabled: true,
    priority: 2,
    confidenceThreshold: 0.4,
    maxEntries: 8000,
    cacheSize: 800,
    seedFile: "seed/coding.json",
    learntFile: "learnt/coding.json",
    apiEndpoints: {
      nextjs: "https://nextjs.org/docs",
      mdn: "https://developer.mozilla.org/en-US/docs/Web",
    },
  },
  philosophy: {
    enabled: true,
    priority: 4,
    confidenceThreshold: 0.3,
    maxEntries: 3000,
    cacheSize: 300,
    seedFile: "seed/philosophy.json",
    learntFile: "learnt/philosophy.json",
  },
  userInfo: {
    enabled: true,
    priority: 1,
    confidenceThreshold: 0.5,
    maxEntries: 2000,
    cacheSize: 200,
    seedFile: "seed/user-profile.json",
    learntFile: "learnt/user-profile.json",
  },
}

export const SYSTEM_CONFIG = {
  name: "ZacAI Enhanced System",
  version: "2.0.0",
  maxConcurrentRequests: 10,
  defaultTimeout: 10000,
  cacheEnabled: true,
  debugMode: false,
  learningEnabled: true,
  performanceMonitoring: true,
}
